apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
  namespace: s2i-test
  labels:
    app: quotes-server-ci
spec:
  type: git
  params:
    - name: url
      value: https://github.com/chetan-rns/quotes-server

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image
  namespace: s2i-test
  labels:
    app: quotes-server-ci
spec:
  params:
  - name: url
    value: quay.io/cbanavik/quotes-server:latest
  - name: digest
    value: latest
  type: image
