apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sample-pipeline
  namespace: s2i-test
  labels:
    app: quotes-server-ci
spec:
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: TLSVERIFY
          value: "false"
      resources:
        inputs:
          - name: source
            resource: source
        outputs:
          - name: image
            resource: image