apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-api-repo-webhook-run
  namespace: s2i-test
  labels:
    app: quotes-server-ci  
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "chetan-rns"
    - name: GitHubUser
      value: "chetan-rns"
    - name: GitHubRepo
      value: "quotes-server"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey  
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: http://quotes-started-listener-s2i-test.apps.ci-ln-3swzpn2-d5d6b.origin-ci-int-aws.dev.rhcloud.com
  timeout: 1000s
  serviceAccount: tekton-triggers-createwebhook
