apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: quotes-pipelinebinding
  namespace: s2i-test
  labels:
    app: quotes-server-ci
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: s2i-test
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: contenttype
      value: $(header.Content-type)