apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: quotes-server
spec:
  selector:
    matchLabels:
      app: quotes-server
  replicas: 1
  template:
    metadata:
      labels:
        app: quotes-server-cd
    spec:
      containers:
        - name: hello-openshift
          image: quay.io/cbanavik/quotes-server:latest
          ports:
            - containerPort: 8080
