apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
  namespace: s2i-test
  labels:
    app: quotes-server-cd
spec:
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
    - name: openshift-client
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: ARGS
          value: 
            - "apply"
            - "-f"
            -  "https://github.com/chetan-rns/quotes-server/blob/master/deploy/manifests.yaml"