apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: deploy-pipelinerun
  labels:
    app: quotes-server-cd
spec:
  pipelineRef:
    name: deploy-pipeline
  resources:
  - name: image
    resourceRef:
      name: image
  - name: source
    resourceRef:
      name: source