apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
  spec:
    resources:
    - name: source
      type: git
    - name: image
      type: image
    tasks:
    - name: openshift-client
      taskRef:
        name: openshift-client
        resources:
          inputs:
          - name: source
            resource: source
          outputs:
          - name: image
            resource: image
      params:
        - name: ARGS
          value: 
                - "apply"
                - "-f"
                -  