apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
  namespace: s2i-test
  labels:
    app: quotes-server-cd
spec:
  tasks:
    - name: openshift-client
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: ARGS
          value: 
            - apply
            - -f
            - https://raw.githubusercontent.com/chetan-rns/quotes-server/master/deploy/manifests.yaml